### ISSUE TITLE
Set reference for the whole alignment

### ISSUE THREAD

**Issue by stas-malavin** [ugeneunipro/ugene#1075]
I'd like to set a reference for the sam/bam alignment in one go, as for example in IGV.
Currently, it's only possible to add a reference to each contig view individually, and when using a multifasta reference (which is always the case with genomes), only the first sequence is added (silently). In case of 100+ (1000+) contigs, manual setting of references is not possible.

**Comment by DmitriiSukhomlinov** [comment]
Hello, 

Unfortunately, there is no such a feature in UGENE, you may add references only manually. We will discuss its necessity with the team and create an issue in our bug tracker system if decide that it is required.

Also, how assembly contig and reference in multifasta are associated to each other? Do they have the same name? Or the same number in the end?

**Comment by stas-malavin** [comment]
Hi Dmitrii,
Thanks for your reply. Yes, reference contigs and sam file share the contig names (because the sam was produced by aligning reads to this reference).
Currently, when the reference is set, you parse the CIGAR string to align it to the alignment of reads, right? So, I assume, this may be done during the database construction step for each contig.
IMHO, setting the reference to the whole alignment is absolutely necessary, as one is usually interested in particular regions of the (reference) genome—how deep are they covered, by what reads, etc., but not in the reads themselves. So, having just the reads is practically senseless. Note, that in IGV, it's just not possible to visualize the alignment without setting the reference.

**Comment by stas-malavin** [comment]
Anyways, when manually selecting a multifasta for the reference, a user must be prompted for the particular sequence to use. Currently, the first sequence in the file is used without throwing any warning or error.

**Comment by DmitriiSukhomlinov** [comment]
OK, I got your request. I created the issue in our bug-tracking system (see [here](https://ugene.dev/tracker/browse/UGENE-7767)) and will try to do it as soon as possible. Thanks for the request!
