### ISSUE TITLE
Loading SAM hangs, when consumed all available RAM by cache and swapping

### ISSUE THREAD

**Issue by stas-malavin** [ugeneunipro/ugene#1076]
The SAM file was just 4.2 Gb. Hanged at 33% (before converting to Ugene database).
When I cleared cache by ```sysctl vm.drop_caches=1```, it went on at ~1%/sec and completed successfully.
vm memory consumption was 8.7Gb/15.4G

**Comment by DmitriiSukhomlinov** [comment]
Hello,

As far as I understand, it looks for you that UGENE stops doing anything when the status bar in the right bottom corner shows 33% and you see the following status thing:

![image](https://user-images.githubusercontent.com/26257527/212019125-e9b5ce08-374f-4840-9f65-caa365818975.png)

In practice, the point is a bit more complicated. The "Loading document" task, which name you may notice on the status bar, is the top-level loading task. This task also have a lot of child tasks. I don't want to confuse you with the the deep explanation of the UGENE inner architecture, just want to say, that if you click the "2: Tasks" button in the bottom-right corner of UGENE at the time you have this 33%, I'm absolutely sure you will see the following picture:

![image](https://user-images.githubusercontent.com/26257527/212018468-24b14026-732a-4b13-99c3-c1e492055b4e.png)

As you may see, the task state called "Sorting BAM" is happening now. This process required the all input file uploaded to RAM (so 4.2 GB will be uploaded to RAM, in your case) and compare all reads to each other each read (in the SAM file one line is one read, file 4.2 GB contains about 42'000'000 reads, so this process requires A LOT OF time). Generally saying - I'm 99% sure, that UGENE doesn't hang, you just need to wait more. 

PS. If you send me this SAM file, I will check how it that really goes.

**Comment by stas-malavin** [comment]
Ok, can't really reproduce it, maybe I was just impatient :) This issue may be closed.
Just a couple of small questions/notes on this functionality (not sure it makes sense to raise new issues for that, but can do it, if it's more convenient for the developers that way).

(1) If I select the sam/bam I already loaded again, UGENE silently rewrites all bam's and the index, creating a new database (appending "_1" to its name). Would be reasonable to warn a user that a database with the corresponding name already exists and ask if she wants to replace it.

(2) Do I understand right, that sorting, indexing, and database creation is done in one thread? Could this be parallelized?

(3) The read information bar that appears when hoovering the read by the mouse pointer doesn't wrap the CIGAR string line. Therefore, in long reads with long CIGAR, left and right edges of the bar go far beyond the screen border, making the text invisible (see the attachment).

(4) I would (optionally?) delete temporary files—bam, sorted bam's, and the index, after creation of a database.

![20230112_122357](https://user-images.githubusercontent.com/17991942/212043907-4a849a7d-42f5-4636-a3b1-11882a9e5813.jpg)

**Comment by DmitriiSukhomlinov** [comment]
That's OK, I can answer here, no problems.

> If I select the sam/bam I already loaded again, UGENE silently rewrites all bam's and the index, creating a new database (appending "_1" to its name). Would be reasonable to warn a user that a database with the corresponding name already exists and ask if she wants to replace it.

The current behavior has been done on purpose. The point here is that even if the database has the same name as the original SAM/BAM file already exists there is no proofs that this is the database, which was created by importing this vary SAM/BAM file. This could be some another database, which were copied/moved to this folder and renamed, or it could be the database created from this SAM/BAM file, but already modified. So, there is no point of replacing it - you can accidentally vanish your own existed data. About warning the user that the database file with the name from the SAM/BAM file already exists - isn't the prefix "_1" already a warning?)

> Do I understand right, that sorting, indexing, and database creation is done in one thread? Could this be parallelized?

We use [samtools](https://github.com/samtools/) for BAM indexing, sorting and so on, and, unfortunately, there is no extra thread opportunities in this tool. Actually, some features are not supposed to be used in multi-threading at all, like the sorting one:
![image](https://user-images.githubusercontent.com/26257527/212243837-e05ffa03-cfaa-4d43-905e-f45ff912d7ca.png)

PS. there is the important moment, that we use a bit obsolete version of samtools (but we have an issue to update it in the nearest future), and, possibly, the latest versions of the tool have more multi-threading features - when we start updating we definitely will check it.

> The read information bar that appears when hoovering the read by the mouse pointer doesn't wrap the CIGAR string line. Therefore, in long reads with long CIGAR, left and right edges of the bar go far beyond the screen border, making the text invisible (see the attachment).

That's a good thing you've found. Actually, I've never seen the assembly, which has a read with such a ling CIGAR. We would be glad if you send us a small example and we definitely will fix it. Just one scaffold would be enough. You may select any scaffold with the long CIGAR -> click right button -> "Export/Import" -> "Export object...", export to another file (preferably choose the "UGENEDB" format" and you can even attach this file here or send it to ugene@unipro.ru

> I would (optionally?) delete temporary files—bam, sorted bam's, and the index, after creation of a database.

Yes, but manually. You need the only UGENEDB file to work with assembly in UGENE.

**Comment by stas-malavin** [comment]
Hi Dmitrii,
Thanks for your explanation.
Considering temp files, maybe it makes sense to add a check button "Delete temporary files after database creation", in the "Open file" menu.
I've sent a ugenedb with an alignment containing long CIGARs to your email.
