### ISSUE TITLE
Ugene doesn't display reverse strand alignments in BAM files

### ISSUE THREAD

**Issue by lokapal** [ugeneunipro/ugene#1115]
Ugene doesn't display alignments to the reverse strand at all (no warnings, no options etc). At the example pictures below you can see that Ugene doesn't display or refer to region near 630000 that is mapped to the reverse strand (blue color at the IGB screenshot) . The same behaviour observed for Ugene 30xx (2020) and for the latest 45.1 version.
It would be good to have it fixed somehow. I attach the reduced bam file to check. Thanks in advance!

[aaa.bam.gz](https://github.com/ugeneunipro/ugene/files/10503839/aaa.bam.gz)
![chr1_igb](https://user-images.githubusercontent.com/6469161/214694850-19889f35-d35c-45d6-bc0d-edd486ca6f6e.png)
![chr1_ugene](https://user-images.githubusercontent.com/6469161/214694855-77f3e0fc-1e8e-42cb-824b-c9dd89324af3.png)

**Comment by yalgaer** [comment]
Thank you for the test data. I will check it and put an update here.

**Comment by yalgaer** [comment]
Looks like reads are in place but for some reason are not reported in the list of groups: 

![image](https://user-images.githubusercontent.com/17791039/214754816-91404a72-d271-47b2-ad69-70699cb64bfa.png)

**Comment by lokapal** [comment]
This alignment is doesn't seen at zoom levels above some:
![chr1](https://user-images.githubusercontent.com/6469161/214798135-a315ac70-bbbb-41fa-a347-0e3db836ad26.png)
![chr1_zoom](https://user-images.githubusercontent.com/6469161/214798165-83119e0b-f66d-4b03-afd4-1f9fc0673e43.png)
As a result (all?) reverse strand alignments are hidden very well...

**Comment by yalgaer** [comment]
The fix is under code review and will be included into the next release in February
