### ISSUE TITLE
Compilation issues on Arch linux

### ISSUE THREAD

**Issue by staalmannen** [ugeneunipro/ugene#12]
Dear, lately there have been compilation issues with the AUR package of UGENE.

https://aur.archlinux.org/packages/ugene/

The compilation complains that isinf and isnan are not defined in hmmer3_funcs.cpp
math.h should be included in hmmer3_funcs.h, so I am not sure what is wrong.

I am guessing if it would be a glibc or gcc-bug, that a lot of packages would suffer from the same...

Are we missing a new Qt dependency?

**Comment by dkandrov** [comment]
Hello, Jens.
Today I will update my Arch linux and try replay your problem.

Thanks for your work! :+1:

**Comment by dkandrov** [comment]
I repeat your error. Problem with new gcc I think.
I attached patch that will fix this problem: [hmmer3.patch.txt](https://github.com/ugeneunipro/ugene/files/218811/hmmer3.patch.txt)

**Comment by dkandrov** [comment]
Also I found one more problem. See patch: [hmmer3.patch2.txt](https://github.com/ugeneunipro/ugene/files/219008/hmmer3.patch2.txt)

**Comment by staalmannen** [comment]
Awesome! Thanks! It compiles now :) I have updated the AUR with your patch
