### ISSUE TITLE
Feature request: line thickness and different colors/palettes in chromatogram viewer

### ISSUE THREAD

**Issue by stas-malavin** [ugeneunipro/ugene#1206]
Dear Ugene developers,
I'm slightly color-blind, and it's hard for me sometimes to recognize the color of small peaks, especially when the chromatogram is not so good and several peaks overlap. My case is very light, so surely others may experience bigger problems. Some software implements special palettes for color-blind, and actually just increasing the thickness of the lines may help a lot.
Thanks!

**Comment by yalgaer** [comment]
Hi Stas!

Your request is very valid. We will keep it as Open until we find resources to implement it.

**Comment by yalgaer** [comment]
Closing as non-active. 
Please re-open with a patch.
