### ISSUE TITLE
"Copy annotation amino acids" copies forward strand translation for reverse strand

### ISSUE THREAD

**Issue by ccgauvin94** [ugeneunipro/ugene#124]
Hi, 

First of all, thank you all so much for your work on UGENE. I honestly can't imagine my life without this tool anymore. It generally does everything I want it to exactly the way I expect it to, and it's awesome. As a structural biologist without great bioinformatics skills, this is an awesome tool. 

I have encountered an issue when trying to copy the amino acid translation of an annotation on the reverse strand. If I select the annotation with a single click, and select "Copy annotation amino acids", or press Ctrl+T (the shortcut key), instead of translating the reverse complement, it instead just translates from the 3'->5' direction. So for instance,  the following gene (cmr5): 

`3'-TTAACCATATGGTAACGCCTCCAATACCTTTTTTATCTCATTTAAGTATGGAAGAATTAGCCTTTCTTCTTTAGACCCAACGCTAGAGGCTACGTCTAGTAATGAATAATATATATCCTTAGGGTCATCTCCTATCCTTATCCGTTTACCTATATTATTTAATACCAAGAGTATAATTGCTACGTAGCCAGCATAACCCGAACCTTCTCTTTTATCCAACTCCTTGCAAATTGAGGCAGGATTTCCTTTACCGCCTGATAGATAATTGTAAATGTCCTTAAAACGATTGTAATCCTCTATTTTTGAAATGTAGAATGTAAATGCAGGAGAAAACCCTATACCTAACATTAGTGATGGAAAATCTGCGGATCTCCTAAGCAATCCGGGTTTAGAAGGCCCGGATTGTATTTTACATTGGGCTGAAACTATTCTCTTACCTATCTCTGTAGCGAATTTAACGTATTCTGATTCCAA-5'`

Translates as:
`LTIW*RLQYLFYLI*VWKN*PFFFRPNARGYV***IIYILRVISYPYPFTYII*YQEYNCYVASITRTFSFIQLLAN*GRISFTA**IIVNVLKTIVILYF*NVECKCRRKPYT*H**WKICGSPKQSGFRRPGLYFTLG*NYSLTYLCSEFNVF*FQ`
when it should translate as:
`LESEYVKFATEIGKRIVSAQCKIQSGPSKPGLLRRSADFPSLMLGIGFSPAFTFYISKIEDYNRFKDIYNYLSGGKGNPASICKELDKREGSGYAGYVAIILLVLNNIGKRIRIGDDPKDIYYSLLDVASSVGSKEERLILPYLNEIKKVLEALPYG*`
because the annotation is clearly on the reverse strand. 

I don't know if this is a bug, or if it's intentional, but if it is intentional I'd recommend clarifying the language to be "Copy annotation direct strand amino acids", and add a keyboard shortcut for "Copy annotation amino acids" since most of the time, I suspect people will be interested in the translation of the gene of interest, not the out of frame translation of a reverse gene. 

Again, thank you all for your work! I appreciate it so much!

**Comment by yalgaer** [comment]
Hi Colin,

You are absolutely right: the annotation copy-actions repeat normal sequence selection copy-actions, however the annotation itself has strand info. If we do not use the strand info when copying the annotation sequence the result may be confusing.

I think we will fix this issue with the next UGENE release planned for September.
Thank you!

**Comment by yalgaer** [comment]
The fix was released as a part of v36.
