### ISSUE TITLE
Compilation fails with gcc6

### ISSUE THREAD

**Issue by Athemis** [ugeneunipro/ugene#13]
Compilation fails on Archlinux using gcc 6.1.1:

`
g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -w -D_REENTRANT -fPIC -DU2_DISTRIBUTION_INFO=sources -DUGENE_VERSION=1.22.0 -DUGENE_VER_MAJOR=1 -DUGENE_VER_MINOR=22 -DUGENE_VER_PATCH=0 -DUGENE_X86_64 -DUGENE_DATA_DIR=\"/usr/share/ugene/data\" -DHI_EXCLUDED -DNDEBUG -DQT_NO_DEBUG -DQT_CORE_LIB -I. -isystem /usr/include/qt5 -isystem /usr/include -Isrc -isystem /usr/include/qt -isystem /usr/include/qt/QtCore -Irelease -I/usr/lib/qt/mkspecs/linux-g++ -o _tmp/obj/release/thread_info.o src/client/linux/dump_writer_common/thread_info.cc
In file included from /usr/include/c++/6.1.1/bits/stl_algo.h:59:0,
                 from /usr/include/c++/6.1.1/algorithm:62,
                 from src/client/linux/crash_generation/crash_generation_client.cc:36:
/usr/include/c++/6.1.1/cstdlib:75:25: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>
                         ^
compilation terminated.
`

This seems to be related to this gcc bug that is triggered by using -isystem in combination with including stdlib:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70129

The response to this bug report sounds like it won't be fixed upstream in gcc as they advise to "Just don't to it".

**Comment by dkandrov** [comment]
Hello, Athemis!

For new GCC need use additional option for qmake: QMAKE_CFLAGS_ISYSTEM=

**Comment by staalmannen** [comment]
This seems to solve the issue :)

slightly off topic: 
I recently got several error reports on my AUR package based on this.
https://aur.archlinux.org/packages/ugene
Since this is the second gcc-related issue I tried to build with clang/libc++ and noticed that several Makefiles have g++ hard-coded. Anyone tried/worked on clang support?

**Comment by dkandrov** [comment]
Hello!
Thanks for issue and sorry for late response.
I removed unneeded `g++` dependency and try to compile with `clang`.
For successful compilation I used following commands:

``` bash
export QMAKESPEC=linux-clang-libc++
qmake -r ugene.pro CONFIG+=x64 QMAKE_CFLAGS_ISYSTEM= \
QMAKE_CXXFLAGS_RELEASE="${CXXFLAGS} -stdlib=libstdc++" \
QMAKE_LFLAGS_RELEASE="${LDFLAGS} -stdlib=libstdc++"
make
```
