### ISSUE TITLE
Q: plans to integrate STAR with e.g. StringTie?

### ISSUE THREAD

**Issue by sklages** [ugeneunipro/ugene#133]
Just curious if there are any plans to integrate some modern tools for RNAseq analysis, e.g. `STAR` aligner, maybe together with `StringTie` transctript assembler?

best,
Sven

**Comment by DmitriiSukhomlinov** [comment]
Hello Sven,
No, we do not have such plans in the nearest future. I can say you, that it is possible to import custom command-line tools in UGENE and integrate them as elements of Workflow Designer. If you are interested in it, you may try to make a simple integration on your own. Take a look at this chapter of UGENE manual: [Custom External Tools](https://ugene.net/wiki/display/UM35/Custom+External+Tools) and [Creating Element](https://ugene.net/wiki/display/UUOUMF34/Creating+Element). Also, there is a new video about this feature will be released with the closest release very soon, you will find it on the [UGENE YouTube channel](https://www.youtube.com/user/UniproUGENE), I hope, on the next week.

**Comment by sklages** [comment]
thanks
