### ISSUE TITLE
48.0 installs files into unconventioinal locations

### ISSUE THREAD

**Issue by yurivict** [ugeneunipro/ugene#1399]
For example, the ```ugene``` executable is installed in ```$PREFIX/ugene``` instead of ```$PREFIX/bin/ugene```.
The manpage is also installed there instead of it being in ```$PREFIX/man/man1/ugene.1.gz```
```plugins``` are under ```$PREFIX``` when before they were in ```$PREFIX/lib/ugene/plugins```.

etc, etc

**Comment by yalgaer** [comment]
We do not officially support any OS distribution except the pre-built and tested packages provided by us.

But we will be glad to accept any patches that improve native builds and do not add require extra maintenance efforts from us.

Please re-open with a patch.
