### ISSUE TITLE
Compilation error on Arch linux

### ISSUE THREAD

**Issue by m-angelov** [ugeneunipro/ugene#14]
Hey!

I get a compilation error and cannot build the package in Arch.

This is the error I get:

"src/MuscleWorkPool.cpp: In constructor ‘U2::MuscleWorkPool::MuscleWorkPool(MuscleContext_, const U2::MuscleTaskSettings&, U2::TaskStateInfo&, int, const U2::MAlignment&, U2::MAlignment&, bool)’:
src/MuscleWorkPool.cpp:32:103: error: cannot convert ‘bool’ to ‘bool_’ in initialization
         bReversed(false), bRight(false), History(NULL), bLockLeft(NULL), bLockRight(false), msaIn(NULL)
                                                                                                       ^
make[2]: **\* [Makefile.Release:2607: _tmp/obj/release/MuscleWorkPool.o] Error 1"

Any ideas? Thanks!

**Comment by dkandrov** [comment]
Hi!

Unfortunately, I cannot reproduce your problem.
How did you try to build UGENE? Which commands did you use?

_P.S.: Sorry for late response, I was in vacation._

**Comment by m-angelov** [comment]
Hello!

It turns out, that the new version (1.23.0) solves my issue :) It builds and works fine, so I guess this could be closed.

Thanks!

---

Just for completeness sake a bit of info about my previous attempts.
My problem was with version 1.22.0 (from the website) and I was using the PKGBUILD in AUR, which was building with:
`qmake-qt5 CONFIG+=x64 QMAKE_CFLAGS_ISYSTEM= PREFIX=/usr -r` and then `make`.

Makepkg.conf as follows:
`CPPFLAGS="-D_FORTIFY_SOURCE=2"`
`CXXFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong"`
`LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro"`
`MAKEFLAGS="-j4"`
