### ISSUE TITLE
GCC5 error: unrecognized command line option '-no-pie'

### ISSUE THREAD

**Issue by Alzimzim** [ugeneunipro/ugene#143]
Новая версия ugene 36.0 не собирается с gcc5
`g++: error: unrecognized command line option '-no-pie'`

**Comment by yalgaer** [comment]
Hi,
the minimal gcc version we support today is 5.4 (>=Ubuntu 16.04 LTS) and -no-pie option is a "must" for the modern Linux systems. Without it ugene executable is recognized as a shared library, but not an executable.

We never build or test with gcc 5.0, so can't guarantee UGENE code can be build or run with it.

I see 2 solutions for you problem:
1) You can always patch your build the way you like.
or
2) You can send us a patch for qmake files that will check for GCC version and enable -no-pie only if gcc version is >= 5.4.

**Comment by Alzimzim** [comment]
> the minimal gcc version we support today is 5.4 (>=Ubuntu 16.04 LTS)

У меня версия >5.4 

```
gcc -v
Используются внутренние спецификации.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib64/gcc/x86_64-unknown-linux-gnu/5.5.0/lto-wrapper
Целевая архитектура: x86_64-unknown-linux-gnu
Параметры конфигурации: ../configure --prefix=/usr --libdir=/usr/lib64 --libexecdir=/usr/lib64 --mandir=/usr/share/man --infodir=/usr/share/info --disable-libjava-multilib --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-java-awt=gtk --enable-gtk-cairo --with-cloog --with-ppl --enable-cloog-backend=isl --disable-cloog-version-check --disable-libssp --disable-libunwind-exceptions --disable-werror --enable-__cxa_atexit --enable-gold=default --with-plugin-ld=/usr/bin/ld --enable-bootstrap --enable-checking=release --enable-gnu-unique-object --enable-languages=c,ada,c++,fortran,go,java,lto,objc,obj-c++ --enable-linker-build-id --enable-plugin --enable-lto --enable-shared --enable-threads=posix --with-system-zlib --with-bugurl=http://bugs.rosalinux.ru/ --with-tune=generic --with-arch_32=i586 --with-multilib-list=m32,m64 --host=x86_64-unknown-linux-gnu --build=x86_64-unknown-linux-gnu --target=x86_64-unknown-linux-gnu
Модель многопоточности: posix
gcc версия 5.5.0 20171010 (ROSA) (Linaro GCC 5.5-2017.10)```

**Comment by yalgaer** [comment]
Вот версия на которой мы тестируем UGENE:
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609

Думаю, на наличие этой опции в gcc 5.x может влиять то, как именно была собрана версия gcc.

Что можно сделать в этом случае: 

1) Сделать дополнительную переменную на которую будет смотреть qmake - "не использовать -no-pie". Проверять эту переменную при работе qmake.

или

2) Вообще не давать эту опцию компилятору из ветки 5.x.  и  использовать ее только с gcc 6.x - именно gcc 6 мы сейчас используем для сборки релиза.

**Comment by yalgaer** [comment]
Скажите какой вариант вам удобнее: мы всегда можем долить его как в мастер так и ветку 36.

Или, возможно, просто убирание этой опции в вашем форке даст самое простое решение.
