### ISSUE TITLE
Is QSpec license  "GPLv2 or later" or "GPLv2 only"?

### ISSUE THREAD

**Issue by variar** [ugeneunipro/ugene#145]
Hi, I'd like to use QSpec in my project, looks very promising. However, my program is a fork of GPLv3 licensed code, and unfortunately FSF states that GPLv3/LGPLv3 and "GPLv2 only" are incompatible. I was unable to find "or later" part in project documentation. It might be I've missed something.

**Comment by atiunov** [comment]
Actually it is "GPLv2 only". But I doubt if it is critical for our company. I've asked supervisors if we can change the license to "GPLv2 or later", but making a decision will take a couple of weeks.

**Comment by yalgaer** [comment]
All our header files have this text:

 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
