### ISSUE TITLE
Complete .desktop file entries

### ISSUE THREAD

**Issue by pgrt** [ugeneunipro/ugene#1611]
Hello,

I noticed the .desktop file lacks keywords and also a wildcard %f for the Exec entry. Applying the enclosed patch fixes this -- you might prefer more relevant keywords, for sure.

Best wishes,

Pierre

[desktop_file_entries.txt](https://github.com/ugeneunipro/ugene/files/15094181/desktop_file_entries.txt)

**Comment by yalgaer** [comment]
Nice! Thank you for the update. Will be merged asap (in 1 day)

**Comment by yalgaer** [comment]
Merged
