### ISSUE TITLE
Using signed char to be independent of the default choice of implementations

### ISSUE THREAD

**Issue by pgrt** [ugeneunipro/ugene#1682]
Hi,

On arm* architectures one gets build failures of ugene 51, see for instance
https://buildd.debian.org/status/fetch.php?pkg=ugene&arch=armhf&ver=51.0%2Bdfsg-1&stamp=1727821103&raw=0

This is because one tries to put -1 in a char, although implementations may define char as being signed or not: this is because one gets narrowing errors on arm* architectures. The simple fix enclosed was enough.

All the best,

-- 
Pierre

[signed_char_neighbour_table.txt](https://github.com/user-attachments/files/17259144/signed_char_neighbour_table.txt)

**Comment by DmitriiSukhomlinov** [comment]
Hello,

As you may see, you are trying to fix the 3rd party tool called "ball". This is an open source tool, which we have implemented into UGENE. We have a unspoken rule for external code, which hasn't been written by us - do not touch it until it is not a 100% bug. That is why this fix doesn't look like essential. I suggest you to offer your fix to [the original ball project](https://github.com/BALL-Project/ball/) and if they approve it, we will upgrade our source code. 

PS. Please, create pull request when you suggests code improvements. Thanks
