### ISSUE TITLE
export GFF: . instead of +

### ISSUE THREAD

**Issue by danpal96** [ugeneunipro/ugene#1683]
version: ugene-51.0-linux-x86-64

`Export annotations` in GFF format has a bug in the strand column, instead of a `+` for the correspondig features it outputs a `.`

![image](https://github.com/user-attachments/assets/9cc1ca0d-0a14-48f7-82ad-aab1ed92656a)
![image](https://github.com/user-attachments/assets/b6a49bc6-cc71-4586-b801-c7359ce7192e)
![image](https://github.com/user-attachments/assets/ecd6f4c3-1be3-439b-a90c-7a6d8a811d04)

**Comment by rasputinkirill** [comment]
Fixed.
https://github.com/ugeneunipro/ugene/pull/1686
