### ISSUE TITLE
INCLUDEPATH+=/usr/include/qt5 shouldn't be in the .pri file

### ISSUE THREAD

**Issue by AlekseyDurachenko** [ugeneunipro/ugene#20]
INCLUDEPATH+=/usr/include/qt5 shouldn't be in the .pri file because it causes a build problem with non-system Qt version(conflict include files). 

if it does not affect the build of the project, it is best to apply the next patch:

```
diff --git a/src/ugene_globals.pri b/src/ugene_globals.pri
index 74dd518..9d41b5a 100644
--- a/src/ugene_globals.pri
+++ b/src/ugene_globals.pri
@@ -8,8 +8,8 @@ DEFINES+=UGENE_VER_MAJOR=$${UGENE_VER_MAJOR}
 DEFINES+=UGENE_VER_MINOR=$${UGENE_VER_MINOR}
 DEFINES+=UGENE_VER_PATCH=$${UGENE_VER_PATCH}

-unix : !macx : INCLUDEPATH-=/usr/include
-unix : !macx : INCLUDEPATH+=/usr/include/qt5 /usr/include
+#unix : !macx : INCLUDEPATH-=/usr/include
+#unix : !macx : INCLUDEPATH+=/usr/include/qt5 /usr/include
 #unix : !macx : INCLUDEPATH =/usr/include/qt5 $$INCLUDEPATH

 # NGS package
```

INCLUDEPATH+=/usr/include/qt5 не должно быть в .pri файлах. Это вызывает проблемы при сборке с не системной версией Qt(возникает конфликт заголовочных файлов). 

Если патч написанный выше никак не влияет на сборку проекта, то лучше его применить. qmake/cmake достаточно умный, чтобы самостоятельно добавить эти пути.

**Comment by epushkova** [comment]
Sorry for the late response.
You're right, absolute paths should not be present in the build info - I've removed these lines. Thank you.
