### ISSUE TITLE
Code Signature missing on MacOS 

### ISSUE THREAD

**Issue by TK5-Tim** [ugeneunipro/ugene#242]
While installing and testing Unipro on MacOS I recognized that the Application has no code signature at all: 
```
> codesign --display /path/to/Unipro\ UGENE.app    
Unipro UGENE.app: code object is not signed at all
```

Code Signature is important for Users and administrators to assure the integrity of an Application. 
Apple has documentation on how to apply this for any application: https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html 

This would really be helpful to make Ugene more trustable and better useable inside the MacOS Framework.

**Comment by yalgaer** [comment]
The issue is fixed in v41.
