### ISSUE TITLE
GC content% of reverse primers is wrong

### ISSUE THREAD

**Issue by Compa0** [ugeneunipro/ugene#32]
When using primer3 plugin to design primers, the all the GC contents of reverse primers is wrong, while the  forward primers are alright. Maybe it's a bug in version 1.27 and 1.28, windows 10.

**Comment by epushkova** [comment]
Thank you for reporting [the issue](https://local.ugene.unipro.ru/tracker/browse/UGENE-5905). We'll fix the bug in the nearest release 1.29.
