### ISSUE TITLE
plugins not loading in Ubuntu 16.04

### ISSUE THREAD

**Issue by trappedinspacetime** [ugeneunipro/ugene#36]
First of all, thank you for developing for such a scientific tool. 
I am on Ubuntu 16.04 platform. I cloned the repository, and built it, and run it like 

      export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:. ; ./ugeneui
from `./ugene/src/_release` directory. It launches successfully, but it's missing all the plugins in `>settings>plugins` though they exist in `./ugene/src/_release/plugins`

I compiled and ran `version 1.28-dev` last year successfully, it loads plugins without prpblem.
Regards.

**Comment by epushkova** [comment]
Hello, Kenn.
Try to reset UGENE settings by deleting the following file: "~/.config/Unipro/UGENE.ini"

Note that you can launch UGENE simply like this: "./ugene -ui" - that line does not require manual setting of LD_LIBRARY_PATH

**Comment by trappedinspacetime** [comment]
@epushkova thank you for responding. I fixed it at last. It's my bad, a few months ago I enabled multiarch support and switched to x86_64 kernel though it is i386 installation. I set `bash` shell to `i386` like

    setarch i386 bash
then recompiled, it built successfully and loads all the plugins.
Thank you for your work.
Regards.
