### ISSUE TITLE
No in silico PCR product when primer overhang extends past the length of the fragment

### ISSUE THREAD

**Issue by mjtadema** [ugeneunipro/ugene#38]
I have a sequence containing only one gene and not much extra bases on either side of the start/stop codons. When I'm trying to design primers that overhang on either side with more bases than the length of the original fragment, I get no PCR products. Adding some random bases fixes this problem.

**Comment by DmitriiSukhomlinov** [comment]
Hello, Ezmagon
Can you, please, describe the scenario in more details and provide the data you use?

**Comment by mjtadema** [comment]
Hi Dmitrii,
Yes of course, I have attached the target gene, the primers i'm trying to use and the target gene with some extra Ts at the 5' end. I'm trying to do an in silico PCR on the target gene with these forward and reverse primers, where the forward primer has a significant overhang that extends past the total length of the gene at the 5' end. 
On the original target gene these primers do not give me any product. When I add some extra Ts to make the fragment long enough so that the primer does not extend past the end of the gene, I do get my intended product. 
This seems to me like unintended behavior.

[ugene_sequences.tar.gz](https://github.com/ugeneunipro/ugene/files/2144644/ugene_sequences.tar.gz)

**Comment by DmitriiSukhomlinov** [comment]
Thanks for your answer.
We checked your data and found out, that the forward primer (OTW-FW) can not be found in the target_gene (and in the target_gene_extended too).  Are you sure that the data is correct? Or, maybe, you set some additional configurations?

**Comment by mjtadema** [comment]
This is correct, since we are introducing a restriction site and a his tag that are not present in the target gene. When i increase the accepted number of mismatches i eventually do get the correct product with the extended gene, but not with the original gene.

**Comment by DmitriiSukhomlinov** [comment]
Thanks for informing us about this, the problem is really can be reproduced. 
The issue about it was created in the bug-tracking system. You can find it here:
https://local.ugene.unipro.ru/tracker/browse/UGENE-6136
This bug will be fixed in the next version (1.31).

Thanks again for informing us.
Best regards,
UGENE team
