### ISSUE TITLE
broken link ensemble.org 

### ISSUE THREAD

**Issue by trappedinspacetime** [ugeneunipro/ugene#40]
I noticed that `http://beta.rest.ensembl.org` is not valid anymore,  `https://rest.ensembl.org` works for the time being.
For test case : https://rest.ensembl.org/sequence/id/ENSG00000205571?content-type=text/x-fasta

**Comment by rasputinkirill** [comment]
Hello!
Thank you for notifying us about the changed link!
We'll fix the issue in the nearest future, so the fix will be included into 1.31.

**Comment by atiunov** [comment]
If you need this feature right now, edit the file DBXRefRegistry.txt, which is placed in the data folder in the UGENE installation folder. You should fix the link to the Ensembl database (line 63). Note that the link is mentioned twice at this line.

**Comment by trappedinspacetime** [comment]
@rasputinkirill @atiunov Thank you for your help, it fixed the issue.

**Comment by atiunov** [comment]
The issue was fixed in release 1.31.0.
A related issue in the tracker: [UGENE-6133](https://local.ugene.unipro.ru/tracker/browse/UGENE-6133)
