### ISSUE TITLE
Compilation error (Qt 5.12)

### ISSUE THREAD

**Issue by staalmannen** [ugeneunipro/ugene#42]
Hi I just saw a commit that said "Qt5.10 support" so I tried on Arch linux with Qt5.12 and this was the error message I got (compilation error in test_runner due to missing 'QtWebKit/QWebView'). A missing include in _tmp/ui/ui_Reporter.h?

`make -f Makefile.Release
make[2]: Entering directory '/home/jens/Devel/AUR/ugene-git/src/ugene/src/plugins/test_runner'
make[2]: *** No rule to make target 'QtWebKit/QWebView', needed by '_tmp/ui/ui_Reporter.h'.  Stop.
make[2]: Leaving directory '/home/jens/Devel/AUR/ugene-git/src/ugene/src/plugins/test_runner'
make[1]: *** [Makefile:40: release] Error 2
make[1]: Leaving directory '/home/jens/Devel/AUR/ugene-git/src/ugene/src/plugins/test_runner'
make: *** [Makefile:2557: sub-src-plugins-test_runner-make_first-ordered] Error 2`

**Comment by atiunov** [comment]
Qt completely removed the WebKit support in version 5.6. They offer to use QtWebEngine. We've migrated to this engine partially, but all changes are in another branch (several branches that ends with "qt-5.7" suffix). We are going to merge changes from these branches to "master" in the nearest two weeks.
If you don't want to wait, build UGENE from "release-qt-5.7" branch, it is exactly what we've released in August.

**Comment by staalmannen** [comment]
Thanks! This got me a bit further:

`g++ -c -pipe -Wno-expansion-to-defined -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -D_REENTRANT -Wall -W -fPIC -DU2_DISTRIBUTION_INFO=sources -DUGENE_VERSION=1.31.0 -DUGENE_VER_MAJOR=1 -DUGENE_VER_MINOR=31 -DUGENE_VER_PATCH=0 -DUGENE_X86_64 -DUGENE_DATA_DIR=\"/usr/share/ugene/data\" -DHI_EXCLUDED -DQT_DLL -DNDEBUG -DPLUGIN_ID=\"external_tool_support\" -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_WEBENGINE_LIB -DQT_WEBENGINECORE_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_SCRIPT_LIB -DQT_WEBCHANNEL_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_POSITIONING_LIB -DQT_CORE_LIB -I. -Isrc -I_tmp -I../../include -isystem /usr/include/qt -isystem /usr/include/qt/QtSvg -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtWebEngine -isystem /usr/include/qt/QtWebEngineCore -isystem /usr/include/qt/QtQuick -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtScript -isystem /usr/include/qt/QtWebChannel -isystem /usr/include/qt/QtQml -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtXml -isystem /usr/include/qt/QtPositioning -isystem /usr/include/qt/QtCore -I_tmp/moc/release -isystem /usr/include/libdrm -I_tmp/ui -I/usr/lib/qt/mkspecs/linux-g++ -o _tmp/obj/release/LengthSettingsWidget.o src/trimmomatic/util/LengthSettingsWidget.cpp
src/trimmomatic/util/LengthSettingsWidget.cpp: In constructor ‘U2::LocalWorkflow::LengthSettingsWidget::LengthSettingsWidget(const QString&)’:
src/trimmomatic/util/LengthSettingsWidget.cpp:35:32: error: expected type-specifier before ‘QIntValidator’
     leLength->setValidator(new QIntValidator(1, std::numeric_limits<int>::max(), this));`


So a typedef issue with QIntValidator ?

**Comment by atiunov** [comment]
Sorry for the delay.
There should be 
`#include <QIntValidator>`
at the beginning of the file.

**Comment by staalmannen** [comment]
I am happy to report that I managed to build UGene from the master branch with Qt 5.12 beta yesterday!

I uploaded a package to the Arch linux AUR
https://aur.archlinux.org/packages/ugene-git/
