### ISSUE TITLE
consensus sequence using Ugene

### ISSUE THREAD

**Issue by computingmachine** [ugeneunipro/ugene#43]
Hi,

I used the samtools to generate the bam file and import to the Ugene, but at some locations along the chromosome, the consensus sequence in Ugene is different from thoses in samtools tview. I choose to use the samtools algorithm in the Ugene. Does anyone know why?

**Comment by atiunov** [comment]
I've checked the source code of the consensus calculation, it is almost the same as in the actual version of samtools. Also I can't see any difference between consensus produced by UGENE realization of samtools algorithm and consensus produced by samtools 1.9 with different sample data.
As I understood from emails, there are no issues in source code, but just an interpretation fallacy.

**Comment by computingmachine** [comment]
Hi,
Thanks for the reply. I have attached the two screenshots of my data. At position 49369237, Ugene has K while samtools has G. Olga has helped to figure this out and the calculation should be K. It looks that when import the reference into samtools, the samtools tview will put G there.

![ugene](https://user-images.githubusercontent.com/35937090/47300417-6a764700-d5ea-11e8-8f51-3badca2ae354.png)
![samtools](https://user-images.githubusercontent.com/35937090/47300435-6fd39180-d5ea-11e8-9f10-5f28c12d74ba.png)
