### ISSUE TITLE
Ярлык на UGENE в ubuntu

### ISSUE THREAD

**Issue by jo80** [ugeneunipro/ugene#45]
Добрый день! Честно говоря я не часто бываю на github по этому напишу в эту ветку. У меня есть желание поучаствовать в разработке UGENE, но я не очень понимаю с какой стороны к этому лучше подойти, вот. И я подумал что можно былобы  исправить баг с установкой ярлыка UGENE в меню ubuntu и linux mint, вот. И я написал bash скрипт который установливает ярлык UGENE в linux меню. Возможно он вам будет интересен. Этот скрипт должен размещатся в той же директории где находится файл ./ugene и запускается из под sudo . Я его проверил на нескольких сборках ubuntu и linux mint , вроде бы всё хорошо работает. Cсылка на скрипт https://yadi.sk/d/LVRfnHNum-s6hQ

**Comment by dkandrov** [comment]
Добрый день!

Спасибо за вашу инициативу!

Однако, аналогичный файл `ugene.desktop` есть [тут](https://github.com/ugeneunipro/ugene/blob/master/installer/_common_data/ugene.desktop). Также есть скрипт, который выполняет регистрацию `mime` типов в системе и устанавливает для пользователя ярлык ugene, он находится [тут](https://github.com/ugeneunipro/ugene/blob/master/installer/_common_data/Associate_files_to_UGENE.sh).

Данный скрипт должен идти в поставке с бинарным пакетом UGENE, вы можете его запустить из-под своего пользователя и он проделает всю работу.

Для нас будет большой помощью, если вы проверите работу этого скрипта на своей системе и напишете сюда результаты проверки. Всё ли сработало и не было ли каких-то проблем.

**Comment by jo80** [comment]
Ну в общем Associate_files_to_UGENE.sh не срабатывает и он лог не записывает по тому что записывать в папку в которой он находится может только root. Причём если его запусить от root то он пишит, что его так нельзя запускать. А что он не срабатывает, так это мне нужно посидеть разобраться.

**Comment by jo80** [comment]
Вобщем я сегодня поковырялся чуть-чуть. У меня Associate_files_to_UGENE.sh вроде бы нормально заработал единственное что этому скрипту нехватает прав для записи лога, но это мелочи. Иконка в меню появляется нормально.

**Comment by jo80** [comment]
Я могу ещё что нибудь сделать.

**Comment by yalgaer** [comment]
@jo80 спасибо за вашу инициативу.
Возможно 2 пути развития вашей работы

1. Если считаете, что текущий метод UGENE можно заменить более совершенным - предлагайте. Можно в виде патча.

2. Если согласны, что текущим метод достаточный, можно сделать следующее
2.1 Предложите, как можно упростить его нахождение/запуск пользователем
2.2 Исправьте проблемы с правами на запись лога о которых вы указали выше.

**Comment by jo80** [comment]
По поводу 1., я предлагаю оставить существующий код.
По поводу 2.1 и 2.2 я подумаю, мне нужно более подробно вникнуть в проект.

**Comment by yalgaer** [comment]
Closing as expired. UGENE now has Help->create desktop shortcut option.
