### ISSUE TITLE
Ошибка сборки 33.0

### ISSUE THREAD

**Issue by Alzimzim** [ugeneunipro/ugene#48]
Собираю ugene с такими параметрами

> %qmake_qt5 -r \
> 	INSTALL_LIBDIR=%{_libdir} \
> 	UGENE_WITHOUT_NON_FREE=1 \
> 	UGENE_EXCLUDE_LIST_ENABLED=1
> %make release

Получаю ошибку линкера. zlib установлен. 

../../_release/libsamtools.a(bam_import.o): In function `ks_getuntil2':
/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/libs_3rdparty/samtools/src/samtools/bam_import.c:20: undefined reference to `gzread'
../../_release/libsamtools.a(bam_import.o): In function `__bam_get_lines':
/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/libs_3rdparty/samtools/src/samtools/bam_import.c:79: undefined reference to `gzdopen'
/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/libs_3rdparty/samtools/src/samtools/bam_import.c:95: undefined reference to `gzclose'
/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/libs_3rdparty/samtools/src/samtools/bam_import.c:79: undefined reference to `gzopen64'
../../_release/libsamtools.a(bam_import.o): In function `sam_header_read2':
/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/libs_3rdparty/samtools/src/samtools/bam_import.c:129: undefined reference to `gzdopen'
../../_release/libsamtools.a(bam_import.o): In function `ks_getc':
/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/libs_3rdparty/samtools/src/samtools/bam_import.c:20: undefined reference to `gzread'
../../_release/libsamtools.a(bam_import.o): In function `sam_header_read2':
/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/libs_3rdparty/samtools/src/samtools/bam_import.c:150: undefined reference to `gzclose'
/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/libs_3rdparty/samtools/src/samtools/bam_import.c:129: undefined reference to `gzopen64'
../../_release/libsamtools.a(bam_import.o): In function `sam_open':
/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/libs_3rdparty/samtools/src/samtools/bam_import.c:487: undefined reference to `gzdopen'
/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/libs_3rdparty/samtools/src/samtools/bam_import.c:487: undefined reference to `gzopen64'
../../_release/libsamtools.a(bam_import.o): In function `sam_close':
/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/libs_3rdparty/samtools/src/samtools/bam_import.c:500: undefined reference to `gzclose'
../../_release/libsamtools.a(razf.o): In function `_razf_write':
/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/libs_3rdparty/samtools/src/samtools/razf.c:197: undefined reference to `deflate'
../../_release/libsamtools.a(razf.o): In function `razf_open_w':
/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/libs_3rdparty/samtools/src/samtools/razf.c:170: undefined reference to `deflateInit2_'
/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/libs_3rdparty/samtools/src/samtools/razf.c:186: undefined reference to `deflateSetHeader'
../../_release/libsamtools.a(razf.o): In function `razf_open_r':
/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/libs_3rdparty/samtools/src/samtools/razf.c:389: undefined reference to `inflateInit2_'
/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/libs_3rdparty/samtools/src/samtools/razf.c:390: undefined reference to `inflateEnd'
../../_release/libsamtools.a(razf.o): In function `_razf_read':
/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/libs_3rdparty/samtools/src/samtools/razf.c:602: undefined reference to `inflate'
../../_release/libsamtools.a(razf.o): In function `razf_flush':
/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/libs_3rdparty/samtools/src/samtools/razf.c:230: undefined reference to `deflate'
../../_release/libsamtools.a(razf.o): In function `_razf_reset_read':
/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/libs_3rdparty/samtools/src/samtools/razf.c:709: undefined reference to `inflateReset'
/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/libs_3rdparty/samtools/src/samtools/razf.c:709: undefined reference to `inflateReset'
../../_release/libsamtools.a(razf.o): In function `razf_close':
/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/libs_3rdparty/samtools/src/samtools/razf.c:826: undefined reference to `inflateEnd'
../../_release/libsamtools.a(razf.o): In function `razf_end_flush':
/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/libs_3rdparty/samtools/src/samtools/razf.c:254: undefined reference to `deflate'
../../_release/libsamtools.a(razf.o): In function `razf_close':
/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/libs_3rdparty/samtools/src/samtools/razf.c:800: undefined reference to `deflateEnd'
../../_release/libsamtools.a(bgzf.o): In function `deflate_block':
/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/libs_3rdparty/samtools/src/samtools/bgzf.c:312: undefined reference to `deflate'
/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/libs_3rdparty/samtools/src/samtools/bgzf.c:314: undefined reference to `deflateEnd'
/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/libs_3rdparty/samtools/src/samtools/bgzf.c:306: undefined reference to `deflateInit2_'
/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/libs_3rdparty/samtools/src/samtools/bgzf.c:330: undefined reference to `deflateEnd'
/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/libs_3rdparty/samtools/src/samtools/bgzf.c:347: undefined reference to `crc32'
/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/libs_3rdparty/samtools/src/samtools/bgzf.c:348: undefined reference to `crc32'
../../_release/libsamtools.a(bgzf.o): In function `inflate_block':
/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/libs_3rdparty/samtools/src/samtools/bgzf.c:385: undefined reference to `inflateInit2_'
/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/libs_3rdparty/samtools/src/samtools/bgzf.c:390: undefined reference to `inflate'
/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/libs_3rdparty/samtools/src/samtools/bgzf.c:396: undefined reference to `inflateEnd'
/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/libs_3rdparty/samtools/src/samtools/bgzf.c:392: undefined reference to `inflateEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile.Release:743: ../../_release/libU2Algorithm.so.1.0.0] Error 1
make[2]: Leaving directory '/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/corelibs/U2Algorithm'
make[1]: *** [Makefile:40: release] Error 2
make[1]: Leaving directory '/home/user/abf/rpmbuild/BUILD/ugene-33.0/src/corelibs/U2Algorithm'
make: *** [Makefile:3015: sub-src-corelibs-U2Algorithm-release_ordered] Error 2

**Comment by dkandrov** [comment]
@Alzimzim Думаю ему нужен не просто `zlib`, а версия для разработчиков (обычно с суфиксом `dev` или `devel`).

Решению проблемы поможет название и версия вашей операционной системы. А также информация о том собиралась ли предыдущая версия UGENE на этой системе.

**Comment by Alzimzim** [comment]
Операционная система [РОСА](http://wiki.rosalab.ru/ru/index.php/ROSA_Desktop_Fresh_R11) 
Конечно, используется девел-пакет `BuildRequires:	pkgconfig(zlib)`
Собиралось и собирались почти все версии за последние несколько лет.

**Comment by atiunov** [comment]
Я попробовал собрать UGENE на дистрибутиве Росы, который я скачал [отсюда](http://wiki.rosalab.ru/ru/index.php/LXQt_R11) (64-bit ISO), у меня не возникло никаких проблем с zlib. У меня zlib была в системе изначально, впрочем дев-версия могла поставиться как зависимость при подготовке среды к сборке UGENE. Собранный UGENE видит zlib, которая находится здесь:
```
ugene@ugene-VirtualBox ~/ugene/src/_release (master) $ ldd libU2Formats.so
        linux-vdso.so.1 =>  (0x00007ffdac46d000)
        libz.so.1 => /lib64/libz.so.1 (0x00007fb13835b000)
        ...
```

Как именно вы собираете UGENE? "BuildRequires" - это ведь строчка из описания пакета? Вы уверены, что там должно быть "zlib", а не "libz"?

**Comment by Alzimzim** [comment]
Я собирал по этому спеку https://pastebin.com/w0kBffA2
Всё же, наверное zlib https://abf.io/import/zlib/blob/rosa2016.1/zlib.spec#lc-103

**Comment by atiunov** [comment]
Я сумел воспроизвести ошибку. Там неверный порядок линковки библиотек. Это проявляется, когда линковщику передаются флаги "-Wl,--no-undefined", что является дефолтным поведением на Росе.
Добавьте применение патча в спеку.
[ugene_U2Algorithm.pri.patch.zip](https://github.com/ugeneunipro/ugene/files/3685775/ugene_U2Algorithm.pri.patch.zip)

**Comment by Alzimzim** [comment]
> Я сумел воспроизвести ошибку. Там неверный порядок линковки библиотек. Это проявляется, когда линковщику передаются флаги "-Wl,--no-undefined", что является дефолтным поведением на Росе.
> Добавьте применение патча в спеку.
> [ugene_U2Algorithm.pri.patch.zip](https://github.com/ugeneunipro/ugene/files/3685775/ugene_U2Algorithm.pri.patch.zip)

Спасибо.
Собралось.
Собрал и добавил в репозиторий Contrib https://abf.io/import/ugene
В ROSA много пользователей вашего приложения.

**Comment by atiunov** [comment]
Добавил фикс в код, со следующей версии все будет нормально.

**Comment by dkandrov** [comment]
> В ROSA много пользователей вашего приложения.

Off topic: @Alzimzim А где это можно увидеть?

**Comment by Alzimzim** [comment]
> > В ROSA много пользователей вашего приложения.
> 
> Off topic: @Alzimzim А где это можно увидеть?

Статистики такой нет. Просто, пользователи часто просят обновить и т.п.

**Comment by dkandrov** [comment]
@Alzimzim Понятно, спасибо)
