### ISSUE TITLE
I installed Qt 5.14 and compiled ugene on Mac OsX - Error message

### ISSUE THREAD

**Issue by cmayer** [ugeneunipro/ugene#50]
The error messages I get are:

In file included from _tmp/moc/release/moc_CreateFragmentDialog.cpp:10:
_tmp/moc/release/../../../src/CreateFragmentDialog.h:48:41: error: implicit instantiation of undefined template
      'QSet<QString>'
    QSet<QString>                       enzymesSelection;
                                   
/Users/cm/Qt/Qt-5.14/5.14.0/clang_64/lib/QtCore.framework/Headers/qlist.h:72:29: note: template is declared here
template <typename T> class QSet;
                         
_tmp/moc/release/moc_CreateFragmentDialog.cpp:87:16: error: static_cast from 'U2::CreateFragmentDialog *' to
      'Ui_CreateFragmentDialog *', which are not related by inheritance, is not allowed
        return static_cast< Ui_CreateFragmentDialog*>(this);
             
_tmp/moc/release/moc_CreateFragmentDialog.cpp:88:21: error: cannot initialize object parameter of type 'QDialog' with an
      expression of type 'U2::CreateFragmentDialog'
    return QDialog::qt_metacast(_clname);
                    
_tmp/moc/release/moc_CreateFragmentDialog.cpp:93:20: error: cannot initialize object parameter of type 'QDialog' with an
      expression of type 'U2::CreateFragmentDialog'
    _id = QDialog::qt_metacall(_c, _id, _a);

**Comment by atiunov** [comment]
I've committed a fix to master.
