### ISSUE TITLE
build error looking for GTGlobals.h

### ISSUE THREAD

**Issue by slyrus** [ugeneunipro/ugene#61]
using the latest source from github (1c3ad6f79), I see the following error:

```
[ 50%] Building CXX object src/plugins/GUITestBase/CMakeFiles/GUITestBase.dir/src/GTDatabaseConfig.cpp.o
In file included from /home/sly/src/ugene/src/plugins/GUITestBase/../../include/U2Test/UGUITest.h:1,
                 from /home/sly/src/ugene/src/plugins/GUITestBase/src/GTDatabaseConfig.cpp:29:
/home/sly/src/ugene/src/plugins/GUITestBase/../../include/U2Test/../../corelibs/U2Test/src/gui_tests/UGUITest.h:27:10: fatal error: GTGlobals.h: No such file or directory
   27 | #include <GTGlobals.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/plugins/GUITestBase/CMakeFiles/GUITestBase.dir/build.make:69: src/plugins/GUITestBase/CMakeFiles/GUITestBase.dir/src/GTDatabaseConfig.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3031: src/plugins/GUITestBase/CMakeFiles/GUITestBase.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Oh, and for completeness, I'm trying to build like so:
```
mkdir build
cd build
cmake "-DCMAKE_INSTALL_PREFIX=/usr/local" ..
make -j14
```

**Comment by DmitriiSukhomlinov** [comment]
Hello!
Unfortunately, CMake isn't optimized good for UGENE compiling. We strongly recommend you to use QMake for this. You need to install Qt (at least version 5.3.2), go to the UGENE folder and run the following commands:
`path\to\qmake -r CONFIG+=x64 ugene.pro`
`make `
 /* CONFIG+=x64 means that you're trying to build 64-bit version, if you need 32-bit skip it */
By the way, do you have any reasons to use exactly CMake? Except the fact, that CMake is kinda "golden standart"?

Best regards,
UGENE team.

**Comment by vedranmiletic** [comment]
@slyrus I had similar issues, in #47 which is now fixed, can you recheck?

**Comment by yalgaer** [comment]
Closing as non-relevant.

The official build system for UGENE is qmake and no-one should build UGENE with CMake today unless he knows what he is doing.

We have CMake files only to simplify coding  for devs who use CLion and never use if for official builds.

We will be happy to accept patches and improvements for CMake however.
