### ISSUE TITLE
Current breakpad requires newer lss (linux-syscalls-support) on some archs.

### ISSUE THREAD

**Issue by StefanBruens** [ugeneunipro/ugene#780]
The breakpad update broke some architectures (e.g. i586), as it removed some compat code. (e.g. it always uses the mmap2 syscall instead of the older mmap).

Please pull a newer lss into the repo.

**Comment by yalgaer** [comment]
Thank you for the suggestion.
Now we are in the feature freeze state and gong to release soon.

Next I will work on this problem.

**Comment by evelinabis** [comment]
Dear @StefanBruens,

Thank you for the suggestion. We have updated breakpad. Has this issue been resolved?

Thank you for using UGENE. Thank you for help and feedback.
Best regards,
Evelina,
The UGENE team.
