### ISSUE TITLE
Linux with glibc >= 2.34 requires updated (or patched) breakpad

### ISSUE THREAD

**Issue by StefanBruens** [ugeneunipro/ugene#781]
From https://chromium.googlesource.com/breakpad/breakpad/+/605c51ed96ad44b34c457bbca320e74e194c317e

> On glibc > 2.33, `SIGSTKSZ` might not be constant (in which case
> it expands to a call to `sysconf` which returns a `long int`); see
> https://sourceware.org/pipermail/libc-alpha/2020-October/118513.html
> 
> Pass unsigned explicitly to std::max, to avoid relying on template
> argument deduction. This works both with the old-style constant
> `SIGSTKSZ` and the new configurable one.

Please cherry-pick the commit above, or do a bulk update of breakpad (+lss).

**Comment by yalgaer** [comment]
Thank you for the suggestion.
Now we are in the feature freeze state and gong to release soon.

Next I will work on this problem.

**Comment by evelinabis** [comment]
Thank you for the suggestion. We have updated breakpad. If you have any questions/comments/suggestions about breakpad, issue #780 still open, you can write your comments there or create a new issue.

Best regards,
Evelina,
The UGENE team.
