### ISSUE TITLE
Built ugene 42 from source on Debian 11 (bullseye). Won't run because it's a 32 bit executable

### ISSUE THREAD

**Issue by Tafnab** [ugeneunipro/ugene#852]
This package cannot be built on Debian 11. Among other things, Werror-* keeps causing failures. It's the compiler's fault. GCC version = 10.2.1.

Compiler finally has segfault while compiling GTTestsRegressionScenarios_6001_7000.h:71:28.  So, there's a problem. Debian 11 repos only contain version 38 of Ugene, which is why I'm trying to build 42.

Is there a way to switch to clang or some other way to get this to build?

**Comment by yalgaer** [comment]
```
qmake -r ugene.pro -spec linux-clang
```

What -Werror errors do you have?
As far as I know we have '-Werror' mode on only if we explicitly set

```
CONFIG+=ugene-warnings-as-errors
```

**Comment by Tafnab** [comment]
If you look at [https://github.com/ugeneunipro/ugene/blob/master/CMakeLists.txt](url) , you will see that CMAKE_COMPILER_IS_GNUCXX turns on a bunch of Werror messages (lines 39-47)

I was building strictly as a CMake project.  I'll try the qmake recipe now.

**Comment by Tafnab** [comment]
> ```
> qmake -r ugene.pro -spec linux-clang
> ```
> 
> What -Werror errors do you have? As far as I know we have '-Werror' mode on only if we explicitly set
> 
> ```
> CONFIG+=ugene-warnings-as-errors
> ```

The qmake build now works.  However, there are possibly some problems remaining.

It now makes to 99%, and issues an error "make: *** [Makefile:103: all] Error 2".  I can run the ugeneui program, so possibly it doesn't matter.  Do you think anything is broken?

The make install doesn't appear to install the program on the system. Instead the executables and libs are in .../ugene-master/dist/ugene-44.0-dev.  I can run the ui from there, but is this really the way Ugene is intended to be installed?

**Comment by yalgaer** [comment]
Hi, ```/dist/ugene-44.0-dev``` is the default install folder. You need to use PREFIX qmake variable to change the installation folder.

About the 99% error: 
could you please attach the clean build log of the failure?

**Comment by yalgaer** [comment]
Closing. Please reopen when needed.
