### ISSUE TITLE
CFBundleShortVersionString and CFBundleVersion of macOS Application not up to date

### ISSUE THREAD

**Issue by TK5-Tim** [ugeneunipro/ugene#904]
The Version numbering `CFBundleShortVersionString` and `CFBundleVersion` in the file `Unipro UGENE.app/Contents/Info.plist` inside the DMG of the MacOS releases do not match up with the version numbers of the releases. They remained unchanged since version 40.0. Fixing that would make it easier to compare different versions.

**Comment by evelinabis** [comment]
Dear @TK5-Tim, @oliverweinm, @aschwanb,

I want to apologize for my recent inactivity on this issue. Now I can report 2 updates.

Firstly, the bug has been fixed.
Secondly, the other day, there has been [a new release](http://ugene.net/download-all.html#:~:text=UGENE%20for%20macOS%20(.dmg)) with corrections.

Thank you for using UGENE and thank you for letting us know about the bug.
Your feedback makes UGENE better. Please do not hesitate to let us know any further wishes or comments.

Best regards,
Evelina,
The UGENE team.

**Comment by TK5-Tim** [comment]
@EvelinaBiserova Thank you very much for addressing the issue! As you said the issue is fixed with the new release. 

Thank you very much again!
