### ISSUE TITLE
Fails on some architectures: src/SendReportDialog.cpp:435:20: error: invalid output constraint '=a' in asm

### ISSUE THREAD

**Issue by yurivict** [ugeneunipro/ugene#919]
On armv7 the error is:
```
src/SendReportDialog.cpp:435:20: error: invalid output constraint '=a' in asm
                 : "=a"(regs[0]), "=b"(regs[1]), "=c"(regs[2]), "=d"(regs[3])
                   ^
1 error generated.
```

If assembly is only for x86/x86_64 please place the check for architecture into cmake scripts.

**Comment by yalgaer** [comment]
Thank you for the report, this part will be removed from non-x86 builds

Do you have any other places where UGENE does not build on ARM?

**Comment by yurivict** [comment]
I only see this failure in the fallout logs at this moment.
I'll let you know if I'll see more failures.
